In [2]:
import opt_einsum as oe
import numpy as np
import torch
import sys
sys.path.append("../../")

In [44]:
from importlib import reload
from mps import simple_mps, tpcp_mps
reload(simple_mps)

<module 'mps.simple_mps' from '/Users/keisuke/Documents/presentation/QC_MPS/mps/notebooks/../../mps/simple_mps.py'>

In [45]:
# def embedding_pixel(X):
#     """
#     class label is assumed to be zero.
#     """
#     # X  = torch.stack([torch.cos(X * np.pi / 2), torch.sin(X * np.pi / 2)], dim=-1)
#     # X = torch.stack([X, 1-X], dim=-1)
#     X = torch.stack([torch.cos(X * np.pi / 2), torch.sin(X * np.pi / 2)], dim=-1)
#     X /= torch.sum(X, dim=-1).unsqueeze(-1)
#     # X = X / torch.norm(X, dim=-1).unsqueeze(-1)
#     return X

In [120]:
def filter_digits(dataset, allowed_digits=[0, 1]):
    """Return a subset of MNIST dataset containing only allowed_digits (0 or 1)."""
    indices = []
    for i in range(len(dataset)):
        _, label = dataset[i]
        if label in allowed_digits:
            indices.append(i)
    return torch.utils.data.Subset(dataset, indices)


def filiter_single_channel(img: torch.Tensor) -> torch.Tensor:
    """
    MNIST is loaded as shape [C, H, W].
    Take only the first channel => shape [H, W].
    """
    return img[0, ...]


def embedding_pixel(batch, label: int = 0):
    """
    Flatten each image from shape [H, W] => [H*W],
    then embed x => [x, 1-x], and L2-normalize along last dim.
    """
    pixel_size = batch.shape[-1] * batch.shape[-2]
    x = batch.view(*batch.shape[:-2], pixel_size)
    x = torch.stack([x, 1 - x], dim=-1)
    x = x / torch.sum(x, dim=-1).unsqueeze(-1)
    return x

In [271]:
###############################################################################
# Loss & Accuracy
###############################################################################
def loss_batch(outputs, labels):
    """
    Binary cross-entropy style loss for outputs in [0, 1].
    For label=0 => prob=outputs[i], else => 1 - outputs[i].
    """
    device = outputs.device
    loss = torch.zeros(1, device=device, dtype=torch.float64)
    for i in range(len(outputs)):
        prob = outputs[i] if labels[i] == 0 else (1 - outputs[i])
        loss -= torch.log(prob + 1e-8)
        # Start of Selection
        if torch.isnan(loss):
            print(f"Loss is NaN at i={i}")
            print(prob, outputs[i], labels[i])
    return loss


def calculate_accuracy(outputs, labels):
    """
    Threshold 0.5 => label 0 or 1. Compare to true labels.
    """
    predictions = (outputs < 0.5).float()
    correct = (predictions == labels).float().sum()
    return correct / labels.numel()

from torchvision import transforms
import torchvision

img_size = 16
transform = transforms.Compose(
    [
        transforms.Resize(img_size),
        transforms.ToTensor(),
        transforms.Lambda(filiter_single_channel),
        transforms.Lambda(embedding_pixel),
        transforms.Lambda(lambda x: x.to(torch.float64)),  # double precision
    ]
)

trainset = torchvision.datasets.MNIST(
    root="data", train=True, download=True, transform=transform
)
# Filter digits 0,1 only
trainset = filter_digits(trainset, allowed_digits=[0, 1])

batch_size = 128

trainloader = torch.utils.data.DataLoader(
    trainset, batch_size=batch_size, shuffle=False
)


In [278]:
# ---------- Build MPS model ----------
N = img_size * img_size
d = l = 2 #data input dimension and class label dimension 
chi_umps = 2
chi_max = 2
reload(simple_mps)

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
smps = simple_mps.SimpleMPS(
    N, 
    2,
    d, 
    l, 
    layers=2,
    device=device, 
    dtype=torch.float64, 
    optimize="greedy",
)


Path is not set, setting...
Found the path
Initialized MPS with random matrices


In [280]:
def accuracy(outputs, target):
    return (outputs.argmax(dim=-1) == target).float().mean()
losses = []
running_loss = 0
running_accuracy = 0
logsoftmax = torch.nn.LogSoftmax(dim=-1)
nnloss = torch.nn.NLLLoss(reduction="mean")
optimizer = torch.optim.Adam(smps.parameters(), lr=0.001)
n_samples = 0
for epoch in range(10):
    for batch_idx, (data, target) in enumerate(trainloader):
        target = target.to(device).to(torch.int64)
        data = data.to(device).permute(1, 0, 2)
        optimizer.zero_grad()
        outputs = smps(data)
        outputs = logsoftmax(outputs)
        loss = nnloss(outputs, target)
        loss.backward()
        optimizer.step()

        data_size = data.shape[1]
        
        # Calculate accuracy
        # print(torch.exp(outputs[:10]), target[:10])
        
        running_loss += loss.item() * data_size
        n_samples += data_size
        
        if batch_idx % 1 == 0:
            avg_loss = running_loss / n_samples
            avg_accuracy = accuracy(outputs, target)
            losses.append(avg_loss)
            running_loss = 0
            running_accuracy = 0
            n_samples = 0
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f} Accuracy: {:.2f}%'.format(
                epoch, batch_idx * data_size, len(trainloader.dataset),
                100. * batch_idx / len(trainloader), avg_loss, avg_accuracy * 100))

Train Epoch: 0 [0/12665 (0%)]	Loss: 0.453299 Accuracy: 57.03%
Train Epoch: 0 [128/12665 (1%)]	Loss: 0.495638 Accuracy: 52.34%
Train Epoch: 0 [256/12665 (2%)]	Loss: 0.440528 Accuracy: 53.91%
Train Epoch: 0 [384/12665 (3%)]	Loss: 0.429119 Accuracy: 53.12%
Train Epoch: 0 [512/12665 (4%)]	Loss: 0.428116 Accuracy: 53.91%
Train Epoch: 0 [640/12665 (5%)]	Loss: 0.412463 Accuracy: 51.56%
Train Epoch: 0 [768/12665 (6%)]	Loss: 0.374117 Accuracy: 59.38%
Train Epoch: 0 [896/12665 (7%)]	Loss: 0.389972 Accuracy: 64.84%
Train Epoch: 0 [1024/12665 (8%)]	Loss: 0.401432 Accuracy: 75.00%
Train Epoch: 0 [1152/12665 (9%)]	Loss: 0.358179 Accuracy: 78.12%
Train Epoch: 0 [1280/12665 (10%)]	Loss: 0.329464 Accuracy: 81.25%


KeyboardInterrupt: 

In [284]:
from mps import tpcp_mps  

reload(tpcp_mps)

tpcp = tpcp_mps.MPSTPCP(N, K=1, d=2, with_identity=True, manifold=tpcp_mps.ManifoldType.EXACT)
tpcp.W.data[:, 1] = 0
tpcp.W.data[:, 0] = 1



In [289]:
tpcp.set_canonical_mps(smps)

tensor([[-0.7238, -0.6897],
        [ 0.0000, -0.0206]], dtype=torch.float64)
tensor([[-1., -0.],
        [-0., -1.]], dtype=torch.float64)


In [290]:
def accuracy(outputs, target):
    correct = (outputs < 0).float() == target.float()
    return correct.float().sum() / target.numel()

out = tpcp(data)

calculate_accuracy(out, target)

tensor(0.5859)

In [ ]:
from mps.StiefelOptimizers import StiefelAdam
from mps.radam import RiemannianAdam
tpcp.set_canonical_mps(smps)
W = torch.zeros(tpcp.L, 2, dtype=torch.float64)
tpcp.initialize_W()
# optimizer = RiemannianAdam(tpcp.parameters(), lr=0.0001)
optimzier = StiefelAdam(tpcp.parameters(), lr=0.0001, expm_method="ForwardEuler")
epochs = 100
for epoch in range(epochs):
    acc_tot = 0
    loss_tot = 0
    for data, target in trainloader:
        optimizer.zero_grad()
        outputs = tpcp(data)
        loss = loss_batch(outputs, target)
        loss.backward()
        optimizer.step()
        acc = calculate_accuracy(outputs, target)
        acc_tot += acc
        loss_tot += loss.item()
        print("Loss: ", loss.item(), "Accuracy: ", acc)

    print(f"Epoch {epoch} / {epochs} / Loss: {loss_tot / len(trainloader)} / Accuracy: {acc_tot / len(trainloader)}")


tensor([[-0.7238, -0.6897],
        [ 0.0000, -0.0206]], dtype=torch.float64)
tensor([[-1., -0.],
        [-0., -1.]], dtype=torch.float64)
Loss:  165.57302303892448 Accuracy:  tensor(0.6719)
Loss:  136.72517229357248 Accuracy:  tensor(0.5859)
Loss:  214.9545905259381 Accuracy:  tensor(0.6406)
Loss:  253.91501380386796 Accuracy:  tensor(0.5859)
Loss:  141.90039993553148 Accuracy:  tensor(0.6250)
Loss:  176.6534983625568 Accuracy:  tensor(0.5703)
Loss:  158.49419001701222 Accuracy:  tensor(0.6406)
Loss:  178.77590048242553 Accuracy:  tensor(0.6641)
Loss:  213.98763350344754 Accuracy:  tensor(0.5781)
Loss:  199.19376933620217 Accuracy:  tensor(0.5781)
Loss:  164.44858785599 Accuracy:  tensor(0.6562)
Loss:  184.13926336246774 Accuracy:  tensor(0.5859)
Loss:  133.45233923736976 Accuracy:  tensor(0.6016)
Loss:  172.4889233851241 Accuracy:  tensor(0.5859)
Loss:  141.63168050465572 Accuracy:  tensor(0.6875)
Loss:  140.35010075661165 Accuracy:  tensor(0.6016)
Loss:  154.4957060693978 Accuracy:

KeyboardInterrupt: 

In [104]:
out = smps(data)
out = logsoftmax(out)
out


tensor([[-1.0300e+01, -3.3639e-05],
        [-1.0873e+01, -1.8957e-05],
        [-1.1319e+01, -1.2135e-05],
        [-1.0072e+01, -4.2227e-05],
        [-1.1331e+01, -1.2001e-05],
        [-8.8451e+00, -1.4410e-04],
        [ 0.0000e+00, -4.8987e+01],
        [-3.3434e-08, -1.7214e+01],
        [-9.8337e+00, -5.3613e-05],
        [-1.0920e+01, -1.8086e-05],
        [-3.4195e-14, -3.1010e+01],
        [-1.0579e+01, -2.5457e-05],
        [-6.0174e-14, -3.0443e+01],
        [-7.9001e+00, -3.7078e-04],
        [ 0.0000e+00, -3.8507e+01],
        [-9.9722e+00, -4.6679e-05],
        [-4.7244e-11, -2.3776e+01],
        [-5.5502e-12, -2.5917e+01],
        [-1.0454e+01, -2.8819e-05],
        [-3.4917e-05, -1.0263e+01],
        [-2.2871e-14, -3.1411e+01],
        [ 0.0000e+00, -4.2346e+01],
        [ 0.0000e+00, -4.4464e+01],
        [-1.0186e+01, -3.7694e-05],
        [-3.7323e-08, -1.7104e+01],
        [ 0.0000e+00, -7.0261e+01],
        [-8.3386e+00, -2.3913e-04],
        [-8.4054e+00, -2.236

In [108]:
out = tpcp(data.permute(1, 0, 2))

# loss_batch(out, target)
(torch.sgn(out) + 1) / 2 + target


tensor([1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
        1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1.,
        0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
        0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
        1., 1.], dtype=torch.float64, grad_fn=<AddBackward0>)