In [1]:
import opt_einsum as oe
import numpy as np
import torch
import sys
sys.path.append("../../")

In [2]:
from importlib import reload
from mps import simple_mps, tpcp_mps
reload(simple_mps)

<module 'mps.simple_mps' from '/Users/keisuke/Documents/presentation/QC_MPS/mps/notebooks/../../mps/simple_mps.py'>

In [3]:
def filter_digits(dataset, allowed_digits=[0, 1]):
    """Return a subset of MNIST dataset containing only allowed_digits (0 or 1)."""
    indices = []
    for i in range(len(dataset)):
        _, label = dataset[i]
        if label in allowed_digits:
            indices.append(i)
    return torch.utils.data.Subset(dataset, indices)


def filiter_single_channel(img: torch.Tensor) -> torch.Tensor:
    """
    MNIST is loaded as shape [C, H, W].
    Take only the first channel => shape [H, W].
    """
    return img[0, ...]


def embedding_pixel(batch, label: int = 0):
    """
    Flatten each image from shape [H, W] => [H*W],
    then embed x => [x, 1-x], and L2-normalize along last dim.
    """
    pixel_size = batch.shape[-1] * batch.shape[-2]
    x = batch.view(*batch.shape[:-2], pixel_size)
    x = torch.stack([x, 1 - x], dim=-1)
    x = x / torch.sum(x, dim=-1).unsqueeze(-1)
    return x

In [4]:
###############################################################################
# Loss & Accuracy
###############################################################################
def loss_batch(outputs, labels):
    """
    Binary cross-entropy style loss for outputs in [0, 1].
    For label=0 => prob=outputs[i], else => 1 - outputs[i].
    """
    device = outputs.device
    loss = torch.zeros(1, device=device, dtype=torch.float64)
    for i in range(len(outputs)):
        prob = outputs[i] if labels[i] == 0 else (1 - outputs[i])
        loss -= torch.log(prob + 1e-8)
        # Start of Selection
        if torch.isnan(loss):
            print(f"Loss is NaN at i={i}")
            print(prob, outputs[i], labels[i])
    return loss


def calculate_accuracy(outputs, labels):
    """
    Threshold 0.5 => label 0 or 1. Compare to true labels.
    """
    predictions = (outputs < 0.5).float()
    correct = (predictions == labels).float().sum()
    return correct / labels.numel()

from torchvision import transforms
import torchvision

img_size = 16
transform = transforms.Compose(
    [
        transforms.Resize(img_size),
        transforms.ToTensor(),
        transforms.Lambda(filiter_single_channel),
        transforms.Lambda(embedding_pixel),
        transforms.Lambda(lambda x: x.to(torch.float64)),  # double precision
    ]
)

trainset = torchvision.datasets.MNIST(
    root="data", train=True, download=True, transform=transform
)
# Filter digits 0,1 only
trainset = filter_digits(trainset, allowed_digits=[0, 1])

batch_size = 128

trainloader = torch.utils.data.DataLoader(
    trainset, batch_size=batch_size, shuffle=False
)


In [5]:
# ---------- Build MPS model ----------
N = img_size * img_size
d = l = 2 #data input dimension and class label dimension 
chi_umps = 2
chi_max = 2
reload(simple_mps)

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
smps = simple_mps.SimpleMPS(
    N, 
    2,
    d, 
    l, 
    layers=2,
    device=device, 
    dtype=torch.float64, 
    optimize="greedy",
)


Path is not set, setting...
Found the path
Initialized MPS with random matrices


In [6]:
def accuracy(outputs, target):
    return (outputs.argmax(dim=-1) == target).float().mean()
losses = []
running_loss = 0
running_accuracy = 0
logsoftmax = torch.nn.LogSoftmax(dim=-1)
nnloss = torch.nn.NLLLoss(reduction="mean")
optimizer = torch.optim.Adam(smps.parameters(), lr=0.001)
n_samples = 0
for epoch in range(1):
    for batch_idx, (data, target) in enumerate(trainloader):
        target = target.to(device).to(torch.int64)
        data = data.to(device).permute(1, 0, 2)
        optimizer.zero_grad()
        outputs = smps(data)
        outputs = logsoftmax(outputs)
        loss = nnloss(outputs, target)
        loss.backward()
        optimizer.step()

        data_size = data.shape[1]
        
        # Calculate accuracy
        # print(torch.exp(outputs[:10]), target[:10])
        
        running_loss += loss.item() * data_size
        n_samples += data_size
        
        if batch_idx % 1 == 0:
            avg_loss = running_loss / n_samples
            avg_accuracy = accuracy(outputs, target)
            losses.append(avg_loss)
            running_loss = 0
            running_accuracy = 0
            n_samples = 0
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f} Accuracy: {:.2f}%'.format(
                epoch, batch_idx * data_size, len(trainloader.dataset),
                100. * batch_idx / len(trainloader), avg_loss, avg_accuracy * 100))

Train Epoch: 0 [0/12665 (0%)]	Loss: 0.693380 Accuracy: 42.97%
Train Epoch: 0 [128/12665 (1%)]	Loss: 0.693088 Accuracy: 47.66%
Train Epoch: 0 [256/12665 (2%)]	Loss: 0.692907 Accuracy: 53.91%
Train Epoch: 0 [384/12665 (3%)]	Loss: 0.692651 Accuracy: 53.12%
Train Epoch: 0 [512/12665 (4%)]	Loss: 0.692105 Accuracy: 53.91%
Train Epoch: 0 [640/12665 (5%)]	Loss: 0.691262 Accuracy: 51.56%
Train Epoch: 0 [768/12665 (6%)]	Loss: 0.688629 Accuracy: 55.47%
Train Epoch: 0 [896/12665 (7%)]	Loss: 0.686424 Accuracy: 52.34%
Train Epoch: 0 [1024/12665 (8%)]	Loss: 0.683018 Accuracy: 49.22%
Train Epoch: 0 [1152/12665 (9%)]	Loss: 0.671369 Accuracy: 53.12%
Train Epoch: 0 [1280/12665 (10%)]	Loss: 0.652862 Accuracy: 54.69%
Train Epoch: 0 [1408/12665 (11%)]	Loss: 0.643309 Accuracy: 50.78%
Train Epoch: 0 [1536/12665 (12%)]	Loss: 0.600847 Accuracy: 57.03%
Train Epoch: 0 [1664/12665 (13%)]	Loss: 0.607812 Accuracy: 45.31%
Train Epoch: 0 [1792/12665 (14%)]	Loss: 0.448316 Accuracy: 62.50%
Train Epoch: 0 [1920/12665 (15

In [11]:
from mps import tpcp_mps  
from mps.trainer import utils

reload(tpcp_mps)

tpcp = tpcp_mps.MPSTPCP(N, K=1, d=2, with_probs=False, with_identity=True, manifold=tpcp_mps.ManifoldType.EXACT)

W = torch.zeros(tpcp.L, 2, dtype=torch.float64)
W[:, 0] = 1
W[:, 1] = 0
tpcp.initialize_W(W, set_r=True)

tpcp.set_canonical_mps(smps)


def accuracy(outputs, target):
    correct = (outputs < 0).float() == target.float()
    return correct.float().sum() / target.numel()

data, target = next(iter(trainloader))
out = tpcp(data)
# out = utils.to_probs(out)

# calculate_accuracy(out, target)

In [13]:
target

tensor([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
        0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 1, 1, 1, 0, 1])

In [12]:
out

tensor([[3.1156e-02, 9.6884e-01],
        [6.0471e-04, 9.9940e-01],
        [2.8713e-04, 9.9971e-01],
        [7.0440e-04, 9.9930e-01],
        [7.1283e-04, 9.9929e-01],
        [4.4731e-02, 9.5527e-01],
        [6.2026e-04, 9.9938e-01],
        [3.8995e-03, 9.9610e-01],
        [4.2654e-02, 9.5735e-01],
        [2.6984e-02, 9.7302e-01],
        [5.7392e-04, 9.9943e-01],
        [8.6022e-02, 9.1398e-01],
        [7.8337e-02, 9.2166e-01],
        [6.1946e-04, 9.9938e-01],
        [7.3164e-02, 9.2684e-01],
        [6.2860e-04, 9.9937e-01],
        [2.1797e-01, 7.8203e-01],
        [5.4114e-02, 9.4589e-01],
        [1.1017e-03, 9.9890e-01],
        [8.1063e-04, 9.9919e-01],
        [4.4000e-02, 9.5600e-01],
        [6.3333e-04, 9.9937e-01],
        [5.8965e-04, 9.9941e-01],
        [3.8646e-02, 9.6135e-01],
        [5.4203e-02, 9.4580e-01],
        [3.3859e-02, 9.6614e-01],
        [7.6338e-04, 9.9924e-01],
        [8.0460e-04, 9.9920e-01],
        [7.5971e-04, 9.9924e-01],
        [6.174

In [19]:
out

tensor([[3.2443e-02, 9.6756e-01],
        [6.2676e-04, 9.9937e-01],
        [3.2211e-04, 9.9968e-01],
        [6.9675e-04, 9.9930e-01],
        [7.0968e-04, 9.9929e-01],
        [4.7081e-02, 9.5292e-01],
        [6.4005e-04, 9.9936e-01],
        [2.9855e-03, 9.9701e-01],
        [5.1718e-02, 9.4828e-01],
        [2.7667e-02, 9.7233e-01],
        [5.9253e-04, 9.9941e-01],
        [7.7886e-02, 9.2211e-01],
        [7.2428e-02, 9.2757e-01],
        [6.3998e-04, 9.9936e-01],
        [7.0679e-02, 9.2932e-01],
        [6.4622e-04, 9.9935e-01],
        [4.0094e-01, 5.9906e-01],
        [5.1513e-02, 9.4849e-01],
        [1.0216e-03, 9.9898e-01],
        [7.9721e-04, 9.9920e-01],
        [4.4820e-02, 9.5518e-01],
        [6.4958e-04, 9.9935e-01],
        [6.0966e-04, 9.9939e-01],
        [3.7886e-02, 9.6211e-01],
        [5.3592e-02, 9.4641e-01],
        [3.2767e-02, 9.6723e-01],
        [7.5833e-04, 9.9924e-01],
        [7.8824e-04, 9.9921e-01],
        [7.3497e-04, 9.9927e-01],
        [6.370

In [103]:
from mps.StiefelOptimizers import StiefelAdam
from mps.radam import RiemannianAdam
optimizer = RiemannianAdam(tpcp.kraus_ops.parameters(), lr=0.0001, betas=(0.9, 0.999))
optimizer_weight = torch.optim.Adam([tpcp.W], lr=0.0001)
# optimzier = StiefelAdam(tpcp.parameters(), lr=0.0001, expm_method="ForwardEuler")
epochs = 100
for epoch in range(epochs):
    acc_tot = 0
    loss_tot = 0
    for data, target in trainloader:
        optimizer.zero_grad()
        optimizer_weight.zero_grad()
        outputs = tpcp(data)
        loss = loss_batch(outputs, target)
        reg_weight = tpcp_mps.regularize_weight(tpcp.W)
        loss_with_weight = loss + reg_weight * 0.1
        loss_with_weight.backward()
        optimizer.step()
        optimizer_weight.step()
        acc = calculate_accuracy(outputs, target)
        acc_tot += acc
        loss_tot += loss.item()
        print("Loss: ", loss.item(), "Reg Weight: ", reg_weight.item(), "Loss with Weight: ", loss_with_weight.item(), "Accuracy: ", acc)

    print(f"Epoch {epoch} / {epochs} / Loss: {loss_tot / len(trainloader)} / Accuracy: {acc_tot / len(trainloader)}")


Loss is NaN at i=0
tensor(-0.9925, dtype=torch.float64, grad_fn=<SelectBackward0>) tensor(-0.9925, dtype=torch.float64, grad_fn=<SelectBackward0>) tensor(0)
Loss is NaN at i=1
tensor(1.9957, dtype=torch.float64, grad_fn=<RsubBackward1>) tensor(-0.9957, dtype=torch.float64, grad_fn=<SelectBackward0>) tensor(1)
Loss is NaN at i=2
tensor(1.9967, dtype=torch.float64, grad_fn=<RsubBackward1>) tensor(-0.9967, dtype=torch.float64, grad_fn=<SelectBackward0>) tensor(1)
Loss is NaN at i=3
tensor(1.9956, dtype=torch.float64, grad_fn=<RsubBackward1>) tensor(-0.9956, dtype=torch.float64, grad_fn=<SelectBackward0>) tensor(1)
Loss is NaN at i=4
tensor(1.9952, dtype=torch.float64, grad_fn=<RsubBackward1>) tensor(-0.9952, dtype=torch.float64, grad_fn=<SelectBackward0>) tensor(1)
Loss is NaN at i=5
tensor(-0.9902, dtype=torch.float64, grad_fn=<SelectBackward0>) tensor(-0.9902, dtype=torch.float64, grad_fn=<SelectBackward0>) tensor(0)
Loss is NaN at i=6
tensor(1.9957, dtype=torch.float64, grad_fn=<RsubBa

AssertionError: weight must sum to 1, got tensor([0.9999, 0.0000], dtype=torch.float64, grad_fn=<SelectBackward0>)

In [104]:
out = smps(data)
out = logsoftmax(out)
out


AssertionError: Number of qubits must match

In [108]:
out = tpcp(data.permute(1, 0, 2))

# loss_batch(out, target)
(torch.sgn(out) + 1) / 2 + target


tensor([1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
        1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1.,
        0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
        0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
        1., 1.], dtype=torch.float64, grad_fn=<AddBackward0>)